#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# UN1CA configuration file for self porting devices (self)

SOURCE_FIRMWARE=$TARGET_FIRMWARE
SOURCE_EXTRA_FIRMWARES=$TARGET_EXTRA_FIRMWARES
SOURCE_API_LEVEL=$TARGET_API_LEVEL
SOURCE_PRODUCT_FIRST_API_LEVEL=$TARGET_PRODUCT_FIRST_API_LEVEL
SOURCE_HAS_SYSTEM_EXT=$TARGET_HAS_SYSTEM_EXT
SOURCE_VENDOR_API_LEVEL=69
SOURCE_SUPER_GROUP_NAME=$TARGET_SUPER_GROUP_NAME

# SEC Product Feature
SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=$TARGET_AUDIO_SUPPORT_ACH_RINGTONE
SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=$TARGET_AUDIO_SUPPORT_DUAL_SPEAKER
SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=$TARGET_AUDIO_SUPPORT_VIRTUAL_VIBRATION
SOURCE_AUTO_BRIGHTNESS_TYPE=$TARGET_AUTO_BRIGHTNESS_TYPE
SOURCE_DVFS_CONFIG_NAME=$TARGET_DVFS_CONFIG_NAME
SOURCE_ESE_CHIP_VENDOR=$TARGET_ESE_CHIP_VENDOR
SOURCE_ESE_COS_NAME=$TARGET_ESE_COS_NAME
SOURCE_FP_SENSOR_CONFIG=$TARGET_FP_SENSOR_CONFIG
SOURCE_HAS_HW_MDNIE=$TARGET_HAS_HW_MDNIE
SOURCE_HAS_MASS_CAMERA_APP=$TARGET_HAS_MASS_CAMERA_APP
SOURCE_HAS_QHD_DISPLAY=$TARGET_HAS_QHD_DISPLAY
SOURCE_HFR_MODE=$TARGET_HFR_MODE
SOURCE_HFR_SUPPORTED_REFRESH_RATE=$TARGET_HFR_SUPPORTED_REFRESH_RATE
SOURCE_HFR_DEFAULT_REFRESH_RATE=$TARGET_HFR_DEFAULT_REFRESH_RATE
SOURCE_HFR_SEAMLESS_BRT=$TARGET_HFR_SEAMLESS_BRT
SOURCE_HFR_SEAMLESS_LUX=$TARGET_HFR_SEAMLESS_LUX
SOURCE_IS_ESIM_SUPPORTED=$TARGET_IS_ESIM_SUPPORTED
SOURCE_MDNIE_SUPPORTED_MODES=$TARGET_MDNIE_SUPPORTED_MODES
SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION=$TARGET_MDNIE_WEAKNESS_SOLUTION_FUNCTION
SOURCE_MULTI_MIC_MANAGER_VERSION=$TARGET_MULTI_MIC_MANAGER_VERSION
SOURCE_SSRM_CONFIG_NAME=$TARGET_SSRM_CONFIG_NAME
SOURCE_SUPPORT_CUTOUT_PROTECTION=$TARGET_SUPPORT_CUTOUT_PROTECTION
